[package]
name = "prjcombine-versal"
version.workspace = true
edition.workspace = true

[dependencies]
bincode.workspace = true
prjcombine-entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-tablegen.workspace = true

[lints]
workspace = true
