[package]
name = "prjcombine-xc2000"
edition.workspace = true
version.workspace = true

[dependencies]
itertools.workspace = true
zstd.workspace = true
bincode.workspace = true
prjcombine-entity.workspace = true
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-tablegen.workspace = true
prjcombine-xilinx-bitstream.workspace = true

[lints]
workspace = true
