[package]
name = "prjcombine_xc9500"
edition.workspace = true
version.workspace = true

[dependencies]
unnamed_entity.workspace = true
serde.workspace = true
bitvec.workspace = true
zstd.workspace = true
bincode.workspace = true
clap.workspace = true
prjcombine_types.workspace = true

[lints]
workspace = true
