[package]
name = "prjcombine-re-lattice-naming"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine-entity.workspace = true
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-ecp.workspace = true
bincode.workspace = true
zstd.workspace = true
clap.workspace = true

[lints]
workspace = true
