[package]
name = "prjcombine_xact_data"
edition.workspace = true
version.workspace = true

[dependencies]
bytes.workspace = true
ndarray.workspace = true
regex.workspace = true
enum-map.workspace = true
clap.workspace = true
unnamed_entity.workspace = true
prjcombine_int.workspace = true

[lints]
workspace = true
