[package]
name = "prjcombine-re-lattice-rawdump"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine-entity.workspace = true
ndarray.workspace = true
serde.workspace = true
bincode.workspace = true
zstd.workspace = true
clap.workspace = true
itertools.workspace = true

[lints]
workspace = true
