[package]
name = "prjcombine-re-xilinx-vivado-dump"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine-entity.workspace = true
serde.workspace = true
simple-error.workspace = true
rayon.workspace = true
clap.workspace = true
indicatif.workspace = true
prjcombine-re-toolchain.workspace = true
prjcombine-re-xilinx-rawdump.workspace = true
prjcombine-re-xilinx-rdbuild.workspace = true

[lints]
workspace = true
