[package]
name = "prjcombine-re-harvester"
edition.workspace = true
version.workspace = true

[dependencies]
prjcombine-entity.workspace = true
prjcombine-types.workspace = true
prjcombine-re-fpga-hammer.workspace = true

[lints]
workspace = true
