[package]
name = "prjcombine-re-xilinx-rd2db-interconnect"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine-entity.workspace = true
assert_matches.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-re-xilinx-naming.workspace = true
prjcombine-re-xilinx-rawdump.workspace = true

[lints]
workspace = true
