[package]
name = "prjcombine-types"
edition.workspace = true
version.workspace = true

[dependencies]
bincode.workspace = true
zstd.workspace = true
jzon.workspace = true
bitvec.workspace = true
itertools.workspace = true
prjcombine-entity.workspace = true

[lints]
workspace = true
