[package]
name = "prjcombine-virtex4"
version.workspace = true
edition.workspace = true

[dependencies]
itertools.workspace = true
zstd.workspace = true
bincode.workspace = true
prjcombine-entity.workspace = true
assert_matches.workspace = true
bimap.workspace = true
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-tablegen.workspace = true
prjcombine-xilinx-bitstream.workspace = true

[lints]
workspace = true
