[package]
name = "prjcombine-coolrunner2"
edition.workspace = true
version.workspace = true

[dependencies]
bincode.workspace = true
zstd.workspace = true
clap.workspace = true
prjcombine-entity.workspace = true
jzon.workspace = true
prjcombine-types.workspace = true
prjcombine-jed.workspace = true

[lints]
workspace = true
