[package]
name = "prjcombine-re-xilinx-rd2db-xc4000"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine-entity.workspace = true
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-xc2000.workspace = true
prjcombine-re-xilinx-rawdump.workspace = true
prjcombine-re-xilinx-naming.workspace = true
prjcombine-re-xilinx-naming-xc2000.workspace = true
prjcombine-re-xilinx-rd2db-interconnect.workspace = true
prjcombine-re-xilinx-rd2db-grid.workspace = true
bincode.workspace = true

[lints]
workspace = true
