[package]
name = "prjcombine-re-lattice-finish"
edition.workspace = true
version.workspace = true

[[bin]]
name = "lattice_finish"
path = "src/main.rs"

[dependencies]
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-ecp.workspace = true
prjcombine-re-lattice-naming.workspace = true
itertools.workspace = true
regex.workspace = true
clap.workspace = true
prjcombine-entity.workspace = true
jzon.workspace = true

[lints]
workspace = true
