[package]
name = "prjcombine-re-xilinx-naming"
edition.workspace = true
version.workspace = true

[dependencies]
bincode.workspace = true
itertools.workspace = true
prjcombine-entity.workspace = true
prjcombine-interconnect.workspace = true

[lints]
workspace = true
