[package]
name = "prjcombine-re-xilinx-naming-virtex2"
edition.workspace = true
version.workspace = true

[dependencies]
prjcombine-entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-virtex2.workspace = true
prjcombine-re-xilinx-naming.workspace = true

[lints]
workspace = true
