[package]
name = "prjcombine-siliconblue"
edition.workspace = true
version.workspace = true

[dependencies]
bitvec.workspace = true
itertools.workspace = true
bincode.workspace = true
zstd.workspace = true
prjcombine-entity.workspace = true
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-tablegen.workspace = true

[lints]
workspace = true
