[package]
name = "prjcombine-interconnect"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine-entity.workspace = true
prjcombine-types.workspace = true
bincode.workspace = true
bimap.workspace = true

[lints]
workspace = true
