[package]
name = "prjcombine-interconnect"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
bincode.workspace = true
bimap.workspace = true
jzon.workspace = true

[lints]
workspace = true
