[package]
name = "prjcombine-xc9500"
edition.workspace = true
version.workspace = true

[dependencies]
prjcombine-entity.workspace = true
zstd.workspace = true
bincode.workspace = true
itertools.workspace = true
clap.workspace = true
prjcombine-types.workspace = true
prjcombine-jed.workspace = true

[lints]
workspace = true
