[package]
name = "prjcombine-re-fpga-hammer"
edition.workspace = true
version.workspace = true

[dependencies]
itertools.workspace = true
rand.workspace = true
bincode.workspace = true
zstd.workspace = true
prjcombine-entity.workspace = true
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-re-hammer.workspace = true

[lints]
workspace = true
