[package]
name = "prjcombine-re-xilinx-rdbuild"
version.workspace = true
edition.workspace = true

[dependencies]
prjcombine-entity.workspace = true
prjcombine-re-xilinx-rawdump.workspace = true

[lints]
workspace = true
