[package]
name = "prjcombine-cli"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
clap.workspace = true
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-xc2000.workspace = true
prjcombine-virtex.workspace = true
prjcombine-virtex2.workspace = true
prjcombine-spartan6.workspace = true
prjcombine-virtex4.workspace = true
prjcombine-ultrascale.workspace = true
prjcombine-versal.workspace = true
prjcombine-siliconblue.workspace = true
prjcombine-ecp.workspace = true
prjcombine-xc9500.workspace = true
prjcombine-xpla3.workspace = true
prjcombine-coolrunner2.workspace = true

[lints]
workspace = true
