[package]
name = "prjcombine-re-xilinx-xact-xc2000"
edition.workspace = true
version.workspace = true

[dependencies]
prjcombine-entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-xc2000.workspace = true
prjcombine-re-xilinx-xact-naming.workspace = true

[lints]
workspace = true
