[book]
authors = ["Wanda"]
language = "en"
src = "src"
title = "Project Combine"

[build]
extra-watch-dirs = ["../databases"]

[preprocessor.prjcombine-docgen]
command = "cargo run -q --bin prjcombine-docgen --"
after = ["index"]

[output.html]
additional-css = ["custom.css"]

[output.html.print]
enable = false

[output.html.search]
enable = false

[output.html.fold]
enable = true
level = 0
