[package]
name = "prjcombine-re-icecube-harvester"
edition.workspace = true
version.workspace = true

[[bin]]
name = "icecube_harvester"
path = "src/main.rs"

[dependencies]
tempfile.workspace = true
clap.workspace = true
rayon.workspace = true
rand.workspace = true
bincode.workspace = true
zip.workspace = true
walkdir.workspace = true
prjcombine-entity.workspace = true
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-siliconblue.workspace = true
prjcombine-re-toolchain.workspace = true
prjcombine-re-harvester.workspace = true
prjcombine-re-sdf.workspace = true
prjcombine-re-fpga-hammer.workspace = true

[lints]
workspace = true
