[package]
name = "prjcombine_virtex_naming"
edition.workspace = true
version.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine_int.workspace = true
prjcombine_xilinx_naming.workspace = true
prjcombine_virtex.workspace = true

[lints]
workspace = true
